### ISSUE TITLE
Fouten laten opborrelen

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/crabpy#68]
https://github.com/OnroerendErfgoed/crabpy/blob/master/crabpy/gateway/capakey.py#L48

Als op dat punt een GatewayRuntimeException wordt gegenereerd wordt die later vervangen door een GatewayResourceNotFoundException. Op dat punt zijn we eigenlijk volledig kwijt wat de oorspronkelijke fout was. Ofwel de oorspronkelijke foutboodschap mee doorsturen naar boven of error logging voorzien bij de root exception.

**Comment by koenedaele** [comment]
Als ik me goed herinner geeft CAPAKEY WS bij een niet bestaand perceel een runtime fout. Ik denk dat er geen verschil was tussen een niet bestaand perceel en een foute call. Zie #49 en OnroerendErfgoed/crabpy_pyramid#25

**Comment by koenedaele** [comment]
Denk dat dit probleem wel kan opgevangen worden met de nieuwe REST service (#45)

**Comment by claeyswo** [comment]
Zou op dit ogenblik zeer goed van pas komen.

**Comment by koenedaele** [comment]
Bij de WS Capakey is het dacht ik niet op te vangen. Geen idee hoe het nu in de REST versie gaat werken. Lijkt me best dat we eerst de bugs oplossen en dan de REST versie deployen op het geoportaal zodat we kunnen zien waar we nu staan.

**Comment by claeyswo** [comment]
Je kan op het moment van oorspronkelijke falen toch de ws.fault loggen?

**Comment by Wim-De-Clercq** [comment]
Sinds python3 heb je `raise xxx from yyy` waar de xxx exception dan een `__cause__` atribuut heeft die yyy bevat.

En met future lib voor python2 compatibility:
```py
# Python 2 and 3:
from future.utils import raise_from

class FileDatabase:
    def __init__(self, filename):
        try:
            self.file = open(filename)
        except IOError as exc:
            raise_from(DatabaseError('failed to open'), exc)
```

Default logging van zo'n error is dan zoals:
```
Traceback (most recent call last):
  File "/home/wim/.PyCharm2018.3/config/scratches/scratch_2.py", line 7, in main
    something()
  File "/home/wim/.PyCharm2018.3/config/scratches/scratch_2.py", line 2, in something
    raise ValueError("Original error")
ValueError: Original error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wim/.PyCharm2018.3/config/scratches/scratch_2.py", line 13, in <module>
    main()
  File "/home/wim/.PyCharm2018.3/config/scratches/scratch_2.py", line 9, in main
    raise TypeError("New error.") from e
TypeError: New error.
```
voor volgende code:
```py
def something():
    raise ValueError("Original error")


def main():
    try:
        something()
    except Exception as e:
        raise TypeError("New error") from e


try:
    main()
except Exception as e:
    print(e.__cause__)  # "Original error"
    print(e)  # "New error"
    raise
```
